### ISSUE TITLE
hud layout doesn't save

### ISSUE THREAD

**Issue by hng12** [postman-client/postman#20]
I used the hud editor to change the layout of the hud. when i quit the game and launched it again the hud layout was reset, but the keybinds were still the same.

**Comment by timo-zzz** [comment]
omg hi hn

**Comment by hng12** [comment]
> omg hi hn

yo

**Comment by moomooooo** [comment]
thats a little weird, the hud config works just fine in the latest version, have you ever run a previous version of postman that isn't 2.100? and can you send me your config.

**Comment by hng12** [comment]
2.100 is my first version. can I add you on discord and communicate with u on there instead? my tag is HИ#0381.

**Comment by moomooooo** [comment]
a discord username cant only have 3 numbers lol

**Comment by moomooooo** [comment]
and it doesn't seem like any last digit works, just add me srgantmoomoo#1052

**Comment by hng12** [comment]
it's HИ#0381 sorry

**Comment by hng12** [comment]
zero three eight one. ill add you instead

**Comment by moomooooo** [comment]
this is fixed.
