### ISSUE TITLE
[BUG] Sprint is not Multidirectional

### ISSUE THREAD

**Issue by linustouchtips** [postman-client/postman#22]
The sprint module doesn't allow sprinting in all directions, only forwards and backward. When moving from side to side, your speed is around (15 kmh) the walking speed meaning the sprint modifier is not applied.

**Comment by ChompChompDead** [comment]
yes remove the mc.player.moveForward > 0 or make a setting for it

**Comment by linustouchtips** [comment]
The "sicko mode" mode setting is supposed to be a multidirectional sprint but it doesn't work because the devs aren't overriding the sprinting value in EntityPlayerSP.

**Comment by linustouchtips** [comment]
swag
